version: "3.7"
services:

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /home/app/service/node_modules
      - /home/app/unbundled-webcomponents/node_modules
      - .:/home/app/service
    command: node ./index.js
    env_file: 
      - env.yml
    depends_on: 
      - minio

  minio:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
    env_file: 
      - env.yml
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2:
