version: "3.7"
services:

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /home/app/node_modules
      - /home/app/openwc/node_modules
      - /home/app/.config
      - /home/app/.npm
      - /home/app/.cache
      - .:/home/app
    command: node ./index.js
    environment:
      - "MINIO_ACCESS_KEY=minioadmin"
      - "MINIO_SECRET_KEY=minioadmin"
      # https://docs.docker.com/docker-for-mac/networking/
      # Use host.docker.internal
      # Add the following to your /etc/hosts file:
      # 127.0.0.1 host.docker.internal
      - "MINIO_URL=host.docker.internal"

  minio:
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2:
