version: '3.7'
services:

  events:
    build: ./events
    ports:
      - 8081:4000
    env_file:
      - .env
    volumes:
      - ./events:/home/node/app
      - /home/node/app/node_modules

  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - .env

volumes:
  db_data: