apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: bundler-service-manager
build:
  artifacts:
  - image: irreversiblespec/bundler-service-events
    context: events
  - image: irreversiblespec/bundler-service-runner
    context: runner
  - image: irreversiblespec/bundler-service-portal
    context: portal
deploy:
  kubectl:
    manifests:
    - events/deployment.yaml
    - runner/deployment.yaml
    - portal/deployment.yaml