apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  annotations:
    nginx.org/client-max-body-size: "500m"
spec:
  rules:
  - host: minio.bundler.heymp.com
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 9000