version: '3.4'
services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build: .
    ports: 
      - 81:80
    env_file:
      - .env