apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: runner
  name: runner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - image: heymp/bundler-service-runner
        imagePullPolicy: Always
        name: runner
        env:
        - name: miniourl
          valueFrom:
            secretKeyRef:
              name: bundler-service
              key: miniourl
        - name: minioaccesskey
          valueFrom:
            secretKeyRef:
              name: minio
              key: accesskey
        - name: miniosecretkey
          valueFrom:
            secretKeyRef:
              name: minio
              key: secretkey
        ports:
        - containerPort: 3000
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  name: runner
  labels:
    app: runner
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: runner

---

  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: runner
  spec:
    rules:
    - host: runner.bundler.heymp.com
      http:
        paths:
        - backend:
            serviceName: runner
            servicePort: 80