version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  bundler-service:
    lang: dockerfile
    handler: .
    image: heymp/bundler-service:latest
    environment:
      miniourl: host.docker.internal
      minioaccesskey: minioadmin
      miniosecretkey: minioadmin